# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
options:
  max-time: 6 
image: rakshans1/ionic-fastlane

pipelines:
  branches:
    

    master:
          - step:
              caches:
              - docker
              script:
              - npm install && ionic cordova platform add android
              # installing scp command
              - fastlane android testt